lomsa-dev/http-mock-adapter

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, lib/http_mock_adapter.dart, lib/src/constants.dart, lib/src/dio_adapter.dart, lib/src/dio_adapter_mockito.dart, lib/src/history.dart, lib/src/http_interceptor.dart, lib/src/mock_provider.dart, lib/src/request_handler.dart, lib/src/utils.dart, pubspec.lock, pubspec.yaml, test/http_mock_adapter_test.dart
=> Add basic variant of DioAdapter and other utilities

lib/http_mock_adapter.dart, lib/src/adapters/dio_adapter.dart, lib/src/handlers/mock_handler.dart, lib/src/handlers/request_handler.dart, lib/src/request.dart
=> Expose Request and RequestMethods to public

lefthook.yaml
=> Add lefthook as Git hooks manager

lib/src/adapter_interface.dart, lib/src/exceptions.dart, lib/src/handlers/request_handler.dart, lib/src/interceptors/http_interceptor.dart, lib/src/request.dart, lib/src/utils.dart, test/http_mock_adapter_test.dart
=> Fix linter errors and warnings

CHANGELOG.md, pubspec.lock
=> add changelog

README.md
=> Apply major update to README.md

example/main.dart, lib/http_mock_adapter.dart, lib/src/adapters/dio_adapter.dart, lib/src/handlers/request_handler.dart, lib/src/history.dart, lib/src/interceptors/dio_interceptor.dart, lib/src/request.dart, test/http_mock_adapter_test.dart
=> Add non-sequential responding and improve result of fetching

example/main.dart
=> added documented examples

CHANGELOG.md, README.md, pubspec.lock, pubspec.yaml
Package's version upped to `0.1.0`.
=> Update package to version 0.1.0

lib/src/handlers/request_handler.dart
=> updated request handler class

example/main.dart
=> improved examples

pubspec.yaml
Please review the [guidelines for contributing](https://github.com/lomsa-dev/http-mock-adapter/blob/develop/CONTRIBUTING.md) to this repository.
---
Please describe your pull request.
Thank you!
=> adding description in pubspec.yaml

lib/src/adapter_interface.dart, lib/src/request.dart
#24 
Adapter interface has been improved, please check issue #24  for more details
accidentally this pull request includes changes of pull request #44
=> Imporved adapter interface

.gitattributes, AUTHORS, CHANGELOG.md, README.md, pubspec.yaml
An attempt to improve package's documentation.
=> Fix linting errors, add AUTHORS metadata, update documentation

.github/workflows/dart-ci.yml
=> Add Continuous Integration for Dart code

lib/src/request.dart
Should fixe some residual issues with https://github.com/lomsa-dev/http-mock-adapter/pull/69 described below.
Match variable names didn't match the actual operation, they were relying on `!match()` and the names reflected positive matching.
Moved null check to `matches` function for less code.
Added default headers to the header check since the adapter adds them on the fetch call.
Signed-off-by: Nick Campbell <nicholas.j.campbell@gmail.com>
=> Match var names & ops. Null chk. Default headers.

lib/src/history.dart, test/history_test.dart, test/http_mock_adapter_test.dart
=> Add a straightforward way to reset history

example/main.dart, lib/src/interfaces.dart, lib/src/request.dart, test/adapters/dio_adapter_test.dart, test/matches_request_test.dart
Resolves #75 and tidies up code.
=> Add query parameters to RequestRouted's methods and tidy code

.gitignore, CHANGELOG.md, README.md, example/main.dart, lib/http_mock_adapter.dart, lib/src/adapters/dio_adapter.dart, lib/src/handlers/request_handler.dart, lib/src/history.dart, lib/src/interceptors/dio_interceptor.dart, lib/src/interfaces.dart, lib/src/request.dart, lib/src/types.dart, pubspec.lock, pubspec.yaml, test/adapters/dio_adapter_test.dart, test/history_test.dart, test/http_mock_adapter_test.dart, test/interceptors/dio_interceptor_test.dart, test/matches_request_test.dart
Applying #87 to `main` branch in order to update <https://pub.dev/packages/http_mock_adapter>.
=> Merge v0.1.6 develop to main

lib/src/matchers/form_data.dart, lib/src/matchers/is_a.dart, lib/src/matchers/matchers.dart, test/matchers/form_data_test.dart, test/matchers/is_a_test.dart
* export `Matcher` base class for easy custom matchers
* add `FormDataMatcher`
* add `IsAMatcher`
* add tests
=> Add isA<T> & FormData matchers

lib/src/matchers/list_param.dart, lib/src/matchers/matchers.dart, test/matchers/list_param_test.dart
* add a matcher that matches dios `ListParam` by comparing value and format
CC @LukaGiorgadze @GiorgiBeriashvili @theiskaa
=> Add ListParam matcher

CHANGELOG.md, README.md, lib/src/adapters/dio_adapter.dart, pubspec.yaml
=> Maximize package score and update pub badge link

CHANGELOG.md, README.md, lib/src/adapters/dio_adapter.dart, pubspec.yaml
=> Maximize package score and update pub badge link (#114)

CHANGELOG.md, README.md, pubspec.yaml, test/request_test.dart
This is a release candidate for version `0.3.2` of the package.
Please see the [CHANGELOG.md](2ecddc0d3e57399e033bec35a8965c9ea7c1fc65) file for brief summary of changes.
=> Update to v0.3.2

lib/src/extensions/matches_request.dart, lib/src/handlers/request_handler.dart, lib/src/mixins/recording.dart, lib/src/types.dart, test/extensions/matches_request_test.dart, test/handlers/request_handler_test.dart, test/mixins/recording_test.dart
Please review the [guidelines for contributing](https://github.com/lomsa-dev/http-mock-adapter/blob/develop/CONTRIBUTING.md) to this repository.
**Tip**: Delete everything but the following section that contains the description of the pull request.
---
For mock http request, not just for unit test. so RequestHandler.reply's parameter data should be function.
so when the real RequestOptions pass in ,the return data can be code with logic.
Please describe your pull request.
Thank you!
=> `RequestHandler.reply`'s parameter data converted to function

README.md, example/main.dart
Adds documentation explanations appropriate for new incoming release: **v0.3.3**
• _Adds docs for #125 & #126_
• _No version updates are available in this PR._
=> Update docs for v0.3.3

lib/src/adapters/dio_adapter.dart, lib/src/exceptions.dart, lib/src/matchers/list_param.dart, lib/src/matchers/matchers.dart, lib/src/mixins/request_handling.dart, pubspec.yaml, test/adapters/dio_adapter_test.dart, test/extensions/matches_request_test.dart, test/handlers/request_handler_test.dart, test/matchers/http_matcher_test.dart, test/matchers/list_param_test.dart, test/mixins/recording_test.dart, test/mixins/request_handling_test.dart
Please review the [guidelines for contributing](https://github.com/lomsa-dev/http-mock-adapter/blob/develop/CONTRIBUTING.md) to this repository.
**Tip**: Delete everything but the following section that contains the description of the pull request.
---
Update packages to the latest versions.
Fix lint warnings and errors.
=> Update Dio 5.0.0

CHANGELOG.md, pubspec.yaml
=> Downgrade collection 1.17.1 -> 1.15.0

.github/workflows/dart-ci.yml, CHANGELOG.md, README.md, pubspec.yaml
Please review the [guidelines for contributing](https://github.com/lomsa-dev/http-mock-adapter/blob/main/CONTRIBUTING.md) to this repository.
**Tip**: Delete everything but the following section that contains the description of the pull request.
---
* fixes #143 
* [Lower dependency constraints to match dio](https://github.com/lomsa-dev/http-mock-adapter/commit/645adc4b25e3d62778fdd9a13e685e6890a33931)
* [Run pipeline on min/stable SDK](https://github.com/lomsa-dev/http-mock-adapter/commit/67dc70e30b70ab602af5cc34bda0095c0cc22b8a) 
* running on different platforms is not required, there is no platform specific code involved in this package
=> Lower dependency constraints to match dio

test/handlers/request_handler_test.dart
Please review the [guidelines for contributing](https://github.com/lomsa-dev/http-mock-adapter/blob/main/CONTRIBUTING.md) to this repository.
**Tip**: Delete everything but the following section that contains the description of the pull request.
---
Fixes https://github.com/lomsa-dev/http-mock-adapter/actions/runs/4845618541/jobs/8634640938
=> remove unused import dart:ffi

.github/workflows/dart-ci.yml, CHANGELOG.md, README.md, pubspec.yaml, test/matchers/list_param_test.dart
- sdk: >=3.0.0
- collection: ^1.18.0
- dio: ^5.3.2
=> Bump up versions
